version: '3.8'

services:
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: APP
      POSTGRES_PASSWORD: APP
      POSTGRES_DB: labprog

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
      - ../common/backend/m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    # Ahora que existe la carpeta cli, entramos ahí
    working_dir: /home/node/cli 
    # Restauramos el comando para que levante el servidor
    command: ng serve --host=0.0.0.0 
    restart: always
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/home/node
  
  testing:
    build:
      context: ./testing
    container_name: testing
    depends_on:
      - backend
    volumes:
      - ./testing:/app
      - /app/node_modules

volumes:
  postgres:
