#Tiene que coincidir con el docker-compose.yml
spring.datasource.url=jdbc:postgresql://database:5432/labprog
spring.datasource.username=APP
spring.datasource.password=APP

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
